swagger: "2.0"
info:
  description: 频道
  version: "1.0.0"
  title: API-频道
host: http://localhost:9004
basePath: /
paths:
  /channel:
    post:
      summary: 增加频道
      parameters:
      - in: body
        name: body
        description: 频道实体
        required: true
        schema:
          $ref: "#/definitions/Channel"
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiResponse'
    get:
      summary: 频道全部列表
      responses:
        200:
          description: 成功
          schema: 
            $ref: '#/definitions/ApiChannelListResponse'
  /channel/{channelId}:
    get:
      summary: 根据ID查询频道
      parameters:
        - name: channelId
          in: path
          description: ChannelID
          required: true
          type: string
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiChannelResponse'
    put:
      summary: 修改频道
      parameters:
        - name: channelId
          in: path
          description: ChannelID
          required: true
          type: string
        - name: body
          in: body
          description: 频道实体
          required: true
          schema:
            $ref: "#/definitions/Channel"
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiResponse'
    delete:
      summary: 根据ID删除频道
      parameters:
        - name: channelId
          in: path
          description: ChannelID
          required: true
          type: string
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiResponse'
  /channel/search:
    post:
      summary: 根据条件查询频道列表 
      parameters:
        - name: body
          in: body
          description: Channel实体类
          required: true
          schema:
            $ref: '#/definitions/Channel'
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiChannelListResponse'
  /channel/search/{page}/{size}:
    post:
      summary: 频道分页
      parameters:
        - name: page
          in: path
          description: 页码
          required: true
          type: integer
          format: int32
        - name: size
          in: path
          description: 页大小
          required: true
          type: integer
          format: int32
        - name: body
          in: body
          description: 查询条件
          required: true
          schema:
            $ref: "#/definitions/Channel"
      responses:
        200:
          description: 查询成功
          schema:
            $ref: '#/definitions/ApiChannelPageResponse'   
definitions:
  Channel:
    type: "object"
    properties:
      id:
        type: "string"        
        description: "ID"
      name:
        type: "string"        
        description: "频道名称"
      state:
        type: "string"        
        description: "状态"

  ChannelList:
    type: "array"
    items: 
      $ref: '#/definitions/Channel'
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
  ApiChannelResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
      data:
        $ref: '#/definitions/Channel'
  ApiChannelListResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
      data:
        $ref: '#/definitions/ChannelList'
  ApiChannelPageResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
      data:
        properties:
          total:
            type: "integer"
            format: "int32"
          rows:
            $ref: '#/definitions/ChannelList'