swagger: "2.0"
info:
  description: 招聘
  version: "1.0.0"
  title: API-招聘
host: localhost:9002
basePath: /
paths:
  /recruit:
    post:
      summary: 增加招聘
      parameters:
      - in: body
        name: body
        description: 招聘实体
        required: true
        schema:
          $ref: "#/definitions/Recruit"
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiResponse'
    get:
      summary: 招聘全部列表
      responses:
        200:
          description: 成功
          schema: 
            $ref: '#/definitions/ApiRecruitListResponse'
  /recruit/{recruitId}:
    get:
      summary: 根据ID查询招聘
      parameters:
        - name: recruitId
          in: path
          description: RecruitID
          required: true
          type: string
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiRecruitResponse'
    put:
      summary: 修改招聘
      parameters:
        - name: recruitId
          in: path
          description: RecruitID
          required: true
          type: string
        - name: body
          in: body
          description: Recruit实体
          required: true
          schema:
            $ref: "#/definitions/Recruit"
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiResponse'
    delete:
      summary: 根据ID删除招聘
      parameters:
        - name: recruitId
          in: path
          description: RecruitID
          required: true
          type: string
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiResponse'
  /recruit/search:
    post:
      summary: 根据条件查询招聘列表 
      parameters:
        - name: body
          in: body
          description: Recruit实体类
          required: true
          schema:
            $ref: '#/definitions/Recruit'
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiRecruitListResponse'
  /recruit/search/{page}/{size}:
    post:
      summary: 招聘分页
      parameters:
        - name: page
          in: path
          description: 页码
          required: true
          type: integer
          format: int32
        - name: size
          in: path
          description: 页大小
          required: true
          type: integer
          format: int32
        - name: body
          in: body
          description: 查询条件
          required: true
          schema:
            $ref: "#/definitions/Recruit"
      responses:
        200:
          description: 查询成功
          schema:
            $ref: '#/definitions/ApiRecruitPageResponse'
  /recruit/search/recommend:
    get:
      summary: 推荐职位
      responses:
        200:
          description: 查询成功
          schema:
            $ref: '#/definitions/ApiRecruitListResponse'
  /recruit/search/newlist:
    get:
      summary: 最新职位
      responses:
        200:
          description: 查询成功
          schema:
            $ref: '#/definitions/ApiRecruitListResponse'
definitions:
  Recruit:
    type: "object"
    properties:
      id:
        type: "string"        
        description: "ID"
      jobname:
        type: "string"        
        description: "职位名称"
      salary:
        type: "string"        
        description: "薪资范围"
      condition:
        type: "string"        
        description: "经验要求"
      education:
        type: "string"        
        description: "学历要求"
      type:
        type: "string"        
        description: "任职方式"
      address:
        type: "string"        
        description: "办公地址"
      eid:
        type: "string"        
        description: "企业ID"
      createtime:
        type: "string"       
        format: 'date-time'        
        description: "创建日期"
      state:
        type: "string"        
        description: "状态"
      url:
        type: "string"        
        description: "网址"
      label:
        type: "string"        
        description: "标签"
      content1:
        type: "string"        
        description: "职位描述"
      content2:
        type: "string"        
        description: "职位要求"

  RecruitList:
    type: "array"
    items: 
      $ref: '#/definitions/Recruit'
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
  ApiRecruitResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
      data:
        $ref: '#/definitions/Recruit'
  ApiRecruitListResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
      data:
        $ref: '#/definitions/RecruitList'
  ApiRecruitPageResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
      data:
        properties:
          total:
            type: "integer"
            format: "int32"
          rows:
            $ref: '#/definitions/RecruitList'
