swagger: "2.0"
info:
  description: "回答"
  version: "1.0.0"
  title: "API列表-回答"
host: localhost:9003
basePath: "/"
schemes:
- "http"
paths:
  '/reply':
    post:
      summary: "增加回答"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/Reply"
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
    get:
      summary: "回答全部列表"
      responses:
        200:
          description: "成功查询到数据"
          schema: 
            $ref: '#/definitions/ApiReplyListResponse'
  '/reply/{replyId}':
    get:
      summary: 根据ID查询回答
      parameters:
        - name: replyId
          in: path
          description: ReplyID
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: 操作成功
          schema:
            $ref: '#/definitions/ApiReplyResponse'
    put:
      summary: "修改Reply"
      parameters:
        - name: replyId
          in: path
          description: 回答ID
          required: true
          type: integer
          format: int64
        - name: "body"
          in: "body"
          description: ""
          required: true
          schema:
            $ref: "#/definitions/Reply"
      responses:
        200:
          description: "修改成功"
          schema:
            $ref: '#/definitions/ApiResponse'
    delete:
      summary: 根据ID删除
      parameters:
        - name: replyId
          in: path
          description: ReplyID
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: 操作成功
          schema:
            $ref: '#/definitions/ApiResponse'
  '/reply/search/{page}/{size}':
    post:
      summary: "回答分页"
      parameters:
        - name: page
          in: path
          description: 页码
          required: true
          type: integer
          format: int64
        - name: size
          in: path
          description: "页大小"
          required: true
          type: integer
          format: int64
        - name: "body"
          in: "body"
          description: "查询条件"
          required: true
          schema:
            $ref: "#/definitions/Reply"
      responses:
        200:
          description: 查询成功
          schema:
            $ref: '#/definitions/ApiReplyPageResponse'
  /reply/problem/{problemId}:
    get:
      summary: "根据问题ID查询回答列表"
      description: "根据问题ID查询回答列表"
      produces:
      - "application/json"
      parameters: 
        - name: problemId
          in: path
          description: "问题ID"
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: "成功查询到数据"
          schema: 
            $ref: '#/definitions/ApiReplyListResponse'
  /reply/save:
    post:
      summary: "回答问题"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/Reply"
      responses:
        200:
          description: 操作成功
          schema:
            $ref: '#/definitions/ApiResponse'
  /reply/list/{page}/{size}:
    get:
      summary: "我的回答列表"
      parameters:
        - name: page
          in: path
          description: 页码
          required: true
          type: integer
          format: int64
        - name: size
          in: path
          description: "页码"
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: 查询成功
          schema:
            $ref: '#/definitions/ApiReplyPageResponse'
definitions:
  Reply:
    type: "object"
    properties:
      id:
        type: "string"        
        description: "编号"
      problemid:
        type: "string"        
        description: "问题ID"
      content:
        type: "string"        
        description: "回答内容"
      createtime:
        type: "string"        
        description: "创建日期"
        format: date
      updatetime:
        type: "string"        
        description: "更新日期"
        format: date
      userid:
        type: "string"        
        description: "回答人ID"
      nikename:
        type: "string"        
        description: "回答人昵称"
  ReplyList:
    type: "array"
    items: 
      $ref: '#/definitions/Reply'
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
  ApiReplyResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
      data:
        $ref: '#/definitions/Reply'
  ApiReplyListResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
      data:
        $ref: '#/definitions/ReplyList'
  ApiReplyPageResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int64"
      flag:
        type: "boolean"
      message:
        type: "string"
      data:
        properties:
          total:
            type: "integer"
            format: "int32"
          rows:
            $ref: '#/definitions/ReplyList'