server:
  port: 9009
spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: 192.168.214.128
aliyun:
  sms:
    accessKeyId: LTAIBkGyM6hDcDOp
    accessKeySecret: bxQhjnIDkqXzjIAGkDNyFbHhR32QPP
    sign_name: tensquare
    template_code: SMS_166372248
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true